name: REXTRUCKS s.r.o.
favicon: null
layout_spectrum: 0.98649
typography_spectrum: 0.5865805230569094
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#565553'
    - '#a4a5a7'
    - '#1c1c1c'
    - '#cbcac6'
  brandStrength: 0.25
  lightness: 0.6909036277793348
  saturation: 0.3536101714707911
  rhythmicContrast: 0.7792457684408873
purpose: []
